apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy
  name: dev
  namespace: default
spec:
  description: The build succeeded!
  name: health
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: 1c31737b9d08298d01adba48ad337f262e17b3d2
  phase: success
  url: https://google.com

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy-load
  name: dev-load-test
  namespace: default
spec:
  description: The build succeeded!
  name: health-load
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: 1c31737b9d08298d01adba48ad337f262e17b3d2
  phase: success
  url: https://google.com

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy
  name: staging
  namespace: default
spec:
  description: The build succeeded!
  name: health
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: c861d9af28bc178d16370e51a3ccfc44d2dbbf69
  phase: success
  url: https://google.com

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy-load
  name: staging-load-test
  namespace: default
spec:
  description: The build succeeded!
  name: health-load
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: c861d9af28bc178d16370e51a3ccfc44d2dbbf69
  phase: success
  url: https://google.com

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy
  name: production
  namespace: default
spec:
  description: The build succeeded!
  name: health
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: 85c32316a7f36106b16c08439c53f9b1a7d081ed
  phase: success
  url: https://google.com

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy-load
  name: production-load-test
  namespace: default
spec:
  description: The build succeeded!
  name: health-load
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: 85c32316a7f36106b16c08439c53f9b1a7d081ed
  phase: success
  url: https://google.com
