apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy
  name: dev
  namespace: default
spec:
  description: The build succeeded!
  name: health
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: 942db1766d87da78e747fb214baa1c12a0d5d4ac
  state: success
  url: https://google.com

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy-load
  name: dev-load-test
  namespace: default
spec:
  description: The build succeeded!
  name: health-load
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: 942db1766d87da78e747fb214baa1c12a0d5d4ac
  state: success
  url: https://google.com

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy
  name: staging
  namespace: default
spec:
  description: The build succeeded!
  name: health
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: 68009e6fada978f6b0c27739c26fc3d53ac88520
  state: success
  url: https://google.com

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy-load
  name: staging-load-test
  namespace: default
spec:
  description: The build succeeded!
  name: health-load
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: 68009e6fada978f6b0c27739c26fc3d53ac88520
  state: success
  url: https://google.com

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy
  name: production
  namespace: default
spec:
  description: The build succeeded!
  name: health
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: 74bb2b52050c08680e9fb0390e3a6e6070f55e96
  state: success
  url: https://google.com

---

apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: promoter
    promoter.argoproj.io/commit-status: healthy-load
  name: production-load-test
  namespace: default
spec:
  description: The build succeeded!
  name: health-load
  repository:
    name: promoter-testing
    owner: zachaller
    scmProviderRef:
      name: scmprovider-sample
  sha: 74bb2b52050c08680e9fb0390e3a6e6070f55e96
  state: success
  url: https://google.com
